name: TrianglesGL pre-commit and post-push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: build docker image
      run: docker build --tag trianglesgl ~/TrianglesGL
    - name: start docker container
      run: docker run --name trianglesgl